#!name=Grammarly

#!desc=Grammarly解锁订阅 subscription.grammarly.com

#!homepage=https://whatshub.top

#!author=yqc007

#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/grammarly.png



[MITM]

hostname = %APPEND% subscription.grammarly.com



[Script]

Grammarly=type=http-response,pattern=^https?:\/\/subscription\.grammarly\.com\/api\/v1\/subscription$,script-path=https://raw.githubusercontent.com/HaoDH/translate-text-script/refs/heads/main/Grammary.js,requires-body=1

